import type { BravermanQuestion } from '@/lib/types'

export const BRAVERMAN_XP_REWARD = 500
export const BRAVERMAN_UNLOCK_LEVEL = 2

/**
 * Braverman Nature Assessment — 140 questions (35 per neurotransmitter).
 * Based on Dr. Eric Braverman's "The Edge Effect" deficiency assessment.
 * Each question rated 0-3: Never=0, Sometimes=1, Often=2, Always=3.
 */
export const BRAVERMAN_QUESTIONS: BravermanQuestion[] = [
  // ============================
  // DOPAMINE DEFICIENCY (1-35)
  // ============================
  { id: 1, neurotransmitter: 'dopamine', question: 'I feel tired or fatigued during the day.' },
  { id: 2, neurotransmitter: 'dopamine', question: 'I need caffeine to get going in the morning.' },
  { id: 3, neurotransmitter: 'dopamine', question: 'I have difficulty concentrating or focusing.' },
  { id: 4, neurotransmitter: 'dopamine', question: 'I feel sluggish or mentally slow.' },
  { id: 5, neurotransmitter: 'dopamine', question: 'I lack motivation to start or complete tasks.' },
  { id: 6, neurotransmitter: 'dopamine', question: 'I crave sugary or high-carb foods.' },
  { id: 7, neurotransmitter: 'dopamine', question: 'I have a low sex drive.' },
  { id: 8, neurotransmitter: 'dopamine', question: 'I feel indifferent or emotionally flat.' },
  { id: 9, neurotransmitter: 'dopamine', question: 'I have trouble waking up in the morning.' },
  { id: 10, neurotransmitter: 'dopamine', question: 'I tend to procrastinate on important tasks.' },
  { id: 11, neurotransmitter: 'dopamine', question: 'I have a hard time staying alert during meetings or lectures.' },
  { id: 12, neurotransmitter: 'dopamine', question: 'I feel bored easily.' },
  { id: 13, neurotransmitter: 'dopamine', question: 'I have difficulty making decisions.' },
  { id: 14, neurotransmitter: 'dopamine', question: 'I have low physical energy or endurance.' },
  { id: 15, neurotransmitter: 'dopamine', question: 'I feel like I am not living up to my potential.' },
  { id: 16, neurotransmitter: 'dopamine', question: 'I have poor hand-eye coordination.' },
  { id: 17, neurotransmitter: 'dopamine', question: 'I experience tremors or shaky hands.' },
  { id: 18, neurotransmitter: 'dopamine', question: 'I feel a need for constant stimulation or excitement.' },
  { id: 19, neurotransmitter: 'dopamine', question: 'I have gained weight without changing my diet.' },
  { id: 20, neurotransmitter: 'dopamine', question: 'I rely on energy drinks, supplements, or stimulants.' },
  { id: 21, neurotransmitter: 'dopamine', question: 'I have trouble finishing projects I start.' },
  { id: 22, neurotransmitter: 'dopamine', question: 'I struggle with addictive tendencies (food, screens, substances).' },
  { id: 23, neurotransmitter: 'dopamine', question: 'I feel detached from activities I used to enjoy.' },
  { id: 24, neurotransmitter: 'dopamine', question: 'I have difficulty with abstract thinking or problem solving.' },
  { id: 25, neurotransmitter: 'dopamine', question: 'I feel physically weak or lack muscle tone.' },
  { id: 26, neurotransmitter: 'dopamine', question: 'I have slow reflexes or reaction time.' },
  { id: 27, neurotransmitter: 'dopamine', question: 'I often feel dissatisfied with life.' },
  { id: 28, neurotransmitter: 'dopamine', question: 'I have difficulty following through on commitments.' },
  { id: 29, neurotransmitter: 'dopamine', question: 'I feel the need to take frequent naps.' },
  { id: 30, neurotransmitter: 'dopamine', question: 'I crave chocolate or sweets intensely.' },
  { id: 31, neurotransmitter: 'dopamine', question: 'I have been told I seem "checked out" or distant.' },
  { id: 32, neurotransmitter: 'dopamine', question: 'I feel lightheaded when I stand up quickly.' },
  { id: 33, neurotransmitter: 'dopamine', question: 'I have low blood pressure.' },
  { id: 34, neurotransmitter: 'dopamine', question: 'I prefer sedentary activities over physical ones.' },
  { id: 35, neurotransmitter: 'dopamine', question: 'I have difficulty handling multiple tasks at once.' },

  // ============================
  // ACETYLCHOLINE DEFICIENCY (36-70)
  // ============================
  { id: 36, neurotransmitter: 'acetylcholine', question: 'I forget where I put things (keys, phone, wallet).' },
  { id: 37, neurotransmitter: 'acetylcholine', question: 'I have difficulty remembering names of people I meet.' },
  { id: 38, neurotransmitter: 'acetylcholine', question: 'I lose my train of thought mid-sentence.' },
  { id: 39, neurotransmitter: 'acetylcholine', question: 'I have trouble recalling recent conversations.' },
  { id: 40, neurotransmitter: 'acetylcholine', question: 'I find it hard to learn new information quickly.' },
  { id: 41, neurotransmitter: 'acetylcholine', question: 'I have difficulty reading and retaining what I read.' },
  { id: 42, neurotransmitter: 'acetylcholine', question: 'I struggle to visualize things in my mind.' },
  { id: 43, neurotransmitter: 'acetylcholine', question: 'I have poor sense of direction.' },
  { id: 44, neurotransmitter: 'acetylcholine', question: 'I cannot easily recall details of past events.' },
  { id: 45, neurotransmitter: 'acetylcholine', question: 'I have difficulty with verbal fluency or finding the right word.' },
  { id: 46, neurotransmitter: 'acetylcholine', question: 'I have trouble following complex instructions.' },
  { id: 47, neurotransmitter: 'acetylcholine', question: 'I feel my creativity has declined.' },
  { id: 48, neurotransmitter: 'acetylcholine', question: 'I have slow mental processing speed.' },
  { id: 49, neurotransmitter: 'acetylcholine', question: 'I struggle to maintain attention for long periods.' },
  { id: 50, neurotransmitter: 'acetylcholine', question: 'I have difficulty recognizing familiar faces.' },
  { id: 51, neurotransmitter: 'acetylcholine', question: 'I experience frequent "tip of the tongue" moments.' },
  { id: 52, neurotransmitter: 'acetylcholine', question: 'I have trouble doing mental arithmetic.' },
  { id: 53, neurotransmitter: 'acetylcholine', question: 'I make more spelling or writing errors than I used to.' },
  { id: 54, neurotransmitter: 'acetylcholine', question: 'I have difficulty understanding abstract concepts.' },
  { id: 55, neurotransmitter: 'acetylcholine', question: 'I feel my memory is worse than others my age.' },
  { id: 56, neurotransmitter: 'acetylcholine', question: 'I struggle to recall facts and figures.' },
  { id: 57, neurotransmitter: 'acetylcholine', question: 'I have trouble concentrating when reading.' },
  { id: 58, neurotransmitter: 'acetylcholine', question: 'I need to re-read paragraphs to understand them.' },
  { id: 59, neurotransmitter: 'acetylcholine', question: 'I feel less sharp mentally than I used to.' },
  { id: 60, neurotransmitter: 'acetylcholine', question: 'I have difficulty with spatial reasoning or puzzles.' },
  { id: 61, neurotransmitter: 'acetylcholine', question: 'I forget appointments or scheduled events.' },
  { id: 62, neurotransmitter: 'acetylcholine', question: 'I have decreased interest in learning new things.' },
  { id: 63, neurotransmitter: 'acetylcholine', question: 'I feel my vocabulary has shrunk.' },
  { id: 64, neurotransmitter: 'acetylcholine', question: 'I have difficulty following movie or book plots.' },
  { id: 65, neurotransmitter: 'acetylcholine', question: 'I struggle with tasks requiring visual imagination.' },
  { id: 66, neurotransmitter: 'acetylcholine', question: 'I have difficulty with hand-writing or typing speed.' },
  { id: 67, neurotransmitter: 'acetylcholine', question: 'I feel my comprehension has declined.' },
  { id: 68, neurotransmitter: 'acetylcholine', question: 'I have trouble multitasking effectively.' },
  { id: 69, neurotransmitter: 'acetylcholine', question: 'I have difficulty remembering lists or sequences.' },
  { id: 70, neurotransmitter: 'acetylcholine', question: 'I feel a general mental fogginess or haziness.' },

  // ============================
  // GABA DEFICIENCY (71-105)
  // ============================
  { id: 71, neurotransmitter: 'gaba', question: 'I feel anxious or nervous without a clear reason.' },
  { id: 72, neurotransmitter: 'gaba', question: 'I experience heart palpitations or a racing heart.' },
  { id: 73, neurotransmitter: 'gaba', question: 'I have tense or tight muscles.' },
  { id: 74, neurotransmitter: 'gaba', question: 'I have difficulty relaxing even when I have free time.' },
  { id: 75, neurotransmitter: 'gaba', question: 'I feel restless or on edge.' },
  { id: 76, neurotransmitter: 'gaba', question: 'I have trouble falling asleep because my mind races.' },
  { id: 77, neurotransmitter: 'gaba', question: 'I startle easily at sudden noises.' },
  { id: 78, neurotransmitter: 'gaba', question: 'I feel overwhelmed by everyday tasks.' },
  { id: 79, neurotransmitter: 'gaba', question: 'I worry excessively about things.' },
  { id: 80, neurotransmitter: 'gaba', question: 'I experience shortness of breath during stressful moments.' },
  { id: 81, neurotransmitter: 'gaba', question: 'I have digestive issues linked to stress (upset stomach, IBS).' },
  { id: 82, neurotransmitter: 'gaba', question: 'I clench my jaw or grind my teeth.' },
  { id: 83, neurotransmitter: 'gaba', question: 'I have difficulty sitting still.' },
  { id: 84, neurotransmitter: 'gaba', question: 'I experience panic attacks or intense anxiety spikes.' },
  { id: 85, neurotransmitter: 'gaba', question: 'I feel I cannot handle one more thing on my plate.' },
  { id: 86, neurotransmitter: 'gaba', question: 'I have cold or sweaty hands.' },
  { id: 87, neurotransmitter: 'gaba', question: 'I feel unsteady or unstable emotionally.' },
  { id: 88, neurotransmitter: 'gaba', question: 'I experience headaches related to tension or stress.' },
  { id: 89, neurotransmitter: 'gaba', question: 'I feel a sense of dread or impending doom.' },
  { id: 90, neurotransmitter: 'gaba', question: 'I have difficulty being patient.' },
  { id: 91, neurotransmitter: 'gaba', question: 'I get irritated or frustrated easily.' },
  { id: 92, neurotransmitter: 'gaba', question: 'I rely on alcohol, food, or substances to calm down.' },
  { id: 93, neurotransmitter: 'gaba', question: 'I have trouble with organization and staying tidy.' },
  { id: 94, neurotransmitter: 'gaba', question: 'I feel nervous in social situations.' },
  { id: 95, neurotransmitter: 'gaba', question: 'I experience back pain or body aches from tension.' },
  { id: 96, neurotransmitter: 'gaba', question: 'I have night sweats or wake up feeling anxious.' },
  { id: 97, neurotransmitter: 'gaba', question: 'I feel like my nervous system is always "on".' },
  { id: 98, neurotransmitter: 'gaba', question: 'I have difficulty delegating tasks to others.' },
  { id: 99, neurotransmitter: 'gaba', question: 'I feel guilty when I take time to relax.' },
  { id: 100, neurotransmitter: 'gaba', question: 'I have ringing in my ears (tinnitus).' },
  { id: 101, neurotransmitter: 'gaba', question: 'I have a trembling or quivering voice when stressed.' },
  { id: 102, neurotransmitter: 'gaba', question: 'I feel on high alert in new environments.' },
  { id: 103, neurotransmitter: 'gaba', question: 'I have difficulty saying "no" to people.' },
  { id: 104, neurotransmitter: 'gaba', question: 'I experience frequent urination when anxious.' },
  { id: 105, neurotransmitter: 'gaba', question: 'I feel my stress levels are higher than most people.' },

  // ============================
  // SEROTONIN DEFICIENCY (106-140)
  // ============================
  { id: 106, neurotransmitter: 'serotonin', question: 'I feel sad or down for no apparent reason.' },
  { id: 107, neurotransmitter: 'serotonin', question: 'I have difficulty falling or staying asleep.' },
  { id: 108, neurotransmitter: 'serotonin', question: 'I crave carbohydrates, bread, or pasta.' },
  { id: 109, neurotransmitter: 'serotonin', question: 'I have low self-esteem or confidence.' },
  { id: 110, neurotransmitter: 'serotonin', question: 'I am easily irritated or have mood swings.' },
  { id: 111, neurotransmitter: 'serotonin', question: 'I feel hopeless about the future.' },
  { id: 112, neurotransmitter: 'serotonin', question: 'I have less interest in activities I once enjoyed.' },
  { id: 113, neurotransmitter: 'serotonin', question: 'I am overly sensitive to criticism.' },
  { id: 114, neurotransmitter: 'serotonin', question: 'I feel disconnected from others.' },
  { id: 115, neurotransmitter: 'serotonin', question: 'I have difficulty controlling my appetite.' },
  { id: 116, neurotransmitter: 'serotonin', question: 'I experience afternoon energy crashes.' },
  { id: 117, neurotransmitter: 'serotonin', question: 'I have obsessive or repetitive thoughts.' },
  { id: 118, neurotransmitter: 'serotonin', question: 'I feel tense or unable to unwind at the end of the day.' },
  { id: 119, neurotransmitter: 'serotonin', question: 'I have difficulty experiencing pleasure.' },
  { id: 120, neurotransmitter: 'serotonin', question: 'I am a perfectionist who gets upset when things are not right.' },
  { id: 121, neurotransmitter: 'serotonin', question: 'I have a negative inner voice or self-talk.' },
  { id: 122, neurotransmitter: 'serotonin', question: 'I find it hard to forgive myself or others.' },
  { id: 123, neurotransmitter: 'serotonin', question: 'I prefer to be alone rather than with others.' },
  { id: 124, neurotransmitter: 'serotonin', question: 'I have chronic pain or fibromyalgia symptoms.' },
  { id: 125, neurotransmitter: 'serotonin', question: 'I experience seasonal mood changes (worse in winter).' },
  { id: 126, neurotransmitter: 'serotonin', question: 'I have difficulty making decisions due to self-doubt.' },
  { id: 127, neurotransmitter: 'serotonin', question: 'I feel angry or resentful more than I should.' },
  { id: 128, neurotransmitter: 'serotonin', question: 'I have a tendency to overeat or binge eat.' },
  { id: 129, neurotransmitter: 'serotonin', question: 'I experience PMS, hormonal mood changes, or hot flashes.' },
  { id: 130, neurotransmitter: 'serotonin', question: 'I have difficulty with impulse control.' },
  { id: 131, neurotransmitter: 'serotonin', question: 'I feel emotionally numb or detached.' },
  { id: 132, neurotransmitter: 'serotonin', question: 'I have constipation or irregular digestion.' },
  { id: 133, neurotransmitter: 'serotonin', question: 'I wake up too early and cannot fall back asleep.' },
  { id: 134, neurotransmitter: 'serotonin', question: 'I am slower to recover from illness or injury.' },
  { id: 135, neurotransmitter: 'serotonin', question: 'I think about food or eating more than I should.' },
  { id: 136, neurotransmitter: 'serotonin', question: 'I have lost interest in intimacy or physical affection.' },
  { id: 137, neurotransmitter: 'serotonin', question: 'I have thoughts of self-harm or worthlessness.' },
  { id: 138, neurotransmitter: 'serotonin', question: 'I have difficulty maintaining routines or habits.' },
  { id: 139, neurotransmitter: 'serotonin', question: 'I experience unexplained crying spells.' },
  { id: 140, neurotransmitter: 'serotonin', question: 'I feel life lacks meaning or purpose.' },
]
