'use client';

import React from 'react';
import Navbar from '@/components/landing/Navbar';
import Footer from '@/components/landing/Footer';

export default function TermsClient() {
    return (
        <div className="min-h-screen bg-background text-ghost">
            <Navbar />
            <main className="max-w-4xl mx-auto px-6 py-32">
                <h1 className="font-heading font-black text-4xl md:text-5xl text-ghost uppercase tracking-tight mb-8">
                    Terms of <span className="text-accent">Service</span>
                </h1>
                <p className="text-ghost/40 font-data text-xs mb-12">Last updated: February 2025</p>

                <div className="space-y-8 text-ghost/70 font-sans text-sm leading-relaxed">
                    <section>
                        <h2 className="font-heading font-bold text-lg text-ghost mb-3">1. Acceptance of Terms</h2>
                        <p>By accessing or using XPLife (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
                    </section>

                    <section>
                        <h2 className="font-heading font-bold text-lg text-ghost mb-3">2. Description of Service</h2>
                        <p>XPLife is a gamified productivity platform that uses AI to generate personalized quests, track habits, and help users achieve their goals through RPG mechanics including XP, levels, streaks, guilds, and leaderboards.</p>
                    </section>

                    <section>
                        <h2 className="font-heading font-bold text-lg text-ghost mb-3">3. User Accounts</h2>
                        <p>You must create an account to use the Service. You are responsible for maintaining the security of your account credentials. You must provide accurate information and keep it updated. You may not share your account with others.</p>
                    </section>

                    <section>
                        <h2 className="font-heading font-bold text-lg text-ghost mb-3">4. Subscription Plans</h2>
                        <p><strong>Free Plan:</strong> Limited features including 1 active goal, 15 AI quests per week, and basic analytics.</p>
                        <p className="mt-2"><strong>Pro Hero (€5.99/month):</strong> Unlimited quests, guilds, boss battles, AI coaching, journal, quest cascade, streak freezes, and advanced analytics.</p>
                        <p className="mt-2"><strong>Guild Master (€49 one-time):</strong> Lifetime access to all Pro features plus exclusive cosmetics and founding member benefits.</p>
                        <p className="mt-2">Prices are in EUR and may be adjusted. You will be notified of any price changes before your next billing cycle.</p>
                    </section>

                    <section>
                        <h2 className="font-heading font-bold text-lg text-ghost mb-3">5. AI-Generated Content</h2>
                        <p>Quests and coaching content are generated by AI based on your profile and goals. While we strive for accuracy and helpfulness, AI-generated content is not a substitute for professional medical, psychological, or fitness advice. Use your own judgment when following AI suggestions.</p>
                    </section>

                    <section>
                        <h2 className="font-heading font-bold text-lg text-ghost mb-3">6. User Conduct</h2>
                        <p>You agree not to: use the Service for illegal purposes, harass other users, manipulate leaderboards or XP systems, attempt to reverse-engineer the Service, or share offensive content in guilds or public features.</p>
                    </section>

                    <section>
                        <h2 className="font-heading font-bold text-lg text-ghost mb-3">7. Intellectual Property</h2>
                        <p>All content, design, graphics, and code of XPLife are owned by us. You retain ownership of content you create (goals, notes). By using the Service, you grant us a license to process your content for service delivery purposes.</p>
                    </section>

                    <section>
                        <h2 className="font-heading font-bold text-lg text-ghost mb-3">8. Cancellation & Refunds</h2>
                        <p>You may cancel your subscription at any time. Access continues until the end of the billing period. Refund requests are handled on a case-by-case basis within 14 days of purchase. Lifetime plans are non-refundable after 30 days.</p>
                    </section>

                    <section>
                        <h2 className="font-heading font-bold text-lg text-ghost mb-3">9. Limitation of Liability</h2>
                        <p>XPLife is provided &quot;as is&quot; without warranties. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability is limited to the amount you paid for the Service in the past 12 months.</p>
                    </section>

                    <section>
                        <h2 className="font-heading font-bold text-lg text-ghost mb-3">10. Changes to Terms</h2>
                        <p>We may update these terms at any time. Continued use after changes constitutes acceptance. Material changes will be communicated via email or in-app notification.</p>
                    </section>

                    <section>
                        <h2 className="font-heading font-bold text-lg text-ghost mb-3">11. Contact</h2>
                        <p>Questions about these terms? Contact us at <a href="mailto:legal@xplife.app" className="text-accent hover:underline">legal@xplife.app</a>.</p>
                    </section>
                </div>
            </main>
            <Footer />
        </div>
    );
}
